using Microsoft.Xna.Framework.Input;

namespace AlkalineThunder.Pandemic.Input
{
    /// <summary>
    /// Represents the parameters of any mouse event that was generated by the scroll wheel.
    /// </summary>
    public sealed class MouseScrollEventArgs : MouseEventArgs
    {
        /// <summary>
        /// Gets an instance of a <see cref="MouseMoveEvent"/> for this event.
        /// </summary>
        public MouseMoveEventArgs MouseMoveEvent
            => new MouseMoveEventArgs(this.MouseState, 0, 0);
        
        /// <summary>
        /// Gets a value indicating the direction in which the mouse scrolled.
        /// </summary>
        public ScrollDirection Direction { get; }

        /// <summary>
        /// Gets the scroll wheel value.
        /// </summary>
        public int WheelValue { get; }

        /// <summary>
        /// Gets the movement of the scroll wheel from its previous position.
        /// </summary>
        public int WheelDelta { get; }

        /// <summary>
        /// Creates a new instance of the <see cref="MouseScrollEventArgs"/> class.
        /// </summary>
        /// <param name="state">The state  of the mouse when the event is fired.</param>
        /// <param name="direction">The direction in which the mouse was scrolled.</param>
        /// <param name="value">The current scroll wheel value.</param>
        /// <param name="delta">The movement of the scrool wheel from its current position.</param>
        public MouseScrollEventArgs(MouseState state, ScrollDirection direction, int value, int delta) : base(state)
        {
            Direction = direction;
            WheelValue = value;
            WheelDelta = delta;
        }
    }
}
